### ISSUE TITLE
Added ctx propagation on all lib function

### ISSUE THREAD

**Issue by alob-mtc** [neymarjimoh/fincra-go#19]
I think we can benefit from introducing context to all lib function. This will give the end developer more control over the lib behaviour from within their applications.

Example
```go
data := &fincra.AcceptChargeBackDto{
  BusinessId: "617fefbe4a68ec99ba6af0be",
  ChargeBackId: "7171892",
}

resp, err := client.AcceptChargeBack(ctx, data)

// ...
// i can trigger some timeout or cancellation base on my business rules
```

**Comment by neymarjimoh** [comment]
Appreciate the suggestion @alob-mtc ! Adding context to our lib functions for increased user control sounds valuable. I'll implement this enhancement.
